language: c

notifications:
  email: true

git:
  depth: 3

before_script:
  - USER_NAME='liu2guang' REPO_NAME='Lua2RTT' 

  - sudo apt-get update 
  - "sudo apt-get -qq install gcc-multilib libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 libsdl-dev || true" 
  - "[ $RTT_TOOL_CHAIN = 'sourcery-arm' ] && curl -s https://launchpadlibrarian.net/287101520/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2 | sudo tar xjf - -C /opt && export RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-5_4-2016q3/bin && /opt/gcc-arm-none-eabi-5_4-2016q3/bin/arm-none-eabi-gcc --version || true" 
  
  - git clone --depth=3 --branch=master https://github.com/RT-Thread/rt-thread.git ../RT-Thread 
  
  - export RTT_ROOT=/home/travis/build/$USER_NAME/RT-Thread
  - "[ x$RTT_CC == x ] && export RTT_CC='gcc' || true"

  - sudo mkdir $RTT_ROOT/bsp/$RTT_BSP/packages 
  - sudo cp    /home/travis/build/$USER_NAME/$REPO_NAME/script/script_bspcfg $RTT_ROOT/bsp/$RTT_BSP/rtconfig.h
  - sudo cp    /home/travis/build/$USER_NAME/$REPO_NAME/script/script_scons  $RTT_ROOT/bsp/$RTT_BSP/packages/SConscript
  - sudo cp -r /home/travis/build/$USER_NAME/$REPO_NAME                      $RTT_ROOT/bsp/$RTT_BSP/packages/$REPO_NAME

script:
  - scons -C $RTT_ROOT/bsp/$RTT_BSP

env:
  - RTT_BSP='imxrt1052-evk' RTT_TOOL_CHAIN='sourcery-arm' 
